server:
  port: 9000

spring:
  application:
    name: online-taxi-gateway
    
#注册中心
eureka: 
  client:
    #设置服务注册中心的URL
    service-url:                      
      defaultZone: http://root:root@eureka-7901:7901/eureka/
  instance: 
    hostname: localhost
    instance-id: online-taxi-gateway 

#用ap代替api-passenger
zuul:
  routes:
    api-passenger: /api/**
  
  #设置什么都不忽略，原来默认忽略Cookie
  sensitive-headers:
  
  #*只能匹配26个字母  ，**任意字母字符
  #ignored-patterns: /*-passenger/**
  
#  ignored-services:
#  - api-passenger