server:
  port: 9000

spring:
  application:
    name: online-taxi-gateway
  #网关
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
      # 全局过滤器为所有的响应加上头部X-Response-festival：国庆节
      - AddResponseHeader=X-Response-festival,国庆节 
      routes:
      #转发到外部网站百度
      - id: router-1
        uri: http://www.baidu.com
        predicates:
        - Path=/bd/**
      #不修饰的转到短信服务
      - id: router-2
        uri: lb://SERVICE-SMS
        predicates:
        - Path=/service-sms-gateway-test/**
          
        
          
    
#注册中心
eureka: 
  client:
    #设置服务注册中心的URL
    service-url:                      
      defaultZone: http://root:root@eureka-7901:7901/eureka/
  instance: 
    hostname: localhost
    instance-id: online-taxi-gateway 

