#服务端口
server: 
  port: 7900

#应用名称及验证账号
spring: 
  application: 
    name: eureka
  security: 
    user: 
      name: root
      password: root

#注册中心
eureka: 
  client:
    #是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false
    register-with-eureka: false
    #是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
    fetch-registry: false
    #设置服务注册中心的URL
    service-url:                      
      defaultZone: http://root:root@eureka-7901:7901/eureka/
  instance: 
    hostname: eureka-7901
