#服务端口
server: 
  port: 9001

#应用名称及验证账号
spring: 
  application: 
    name: api-passenger
  redis:    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 2000  mvc:    servlet:      load-on-startup: 1
  #zipkin
  zipkin:
    base-url: http://localhost:9411/
    #采样比例1，百分之八采样
  sleuth:
    sampler:
      rate: 1  #注册中心
eureka: 
#  server:
#    enable-self-preservation: false       #关闭保护机制
#    eviction-interval-timer-in-ms: 2000   #剔除失效服务间隔,单位毫秒
  client:
    #设置服务注册中心的URL
    service-url:                      
      defaultZone: http://root:root@eureka-7901:7901/eureka/
  instance: 
    hostname: localhost
    instance-id: api-passenger
    
feign:
  #开启feignhystrix  hystrix:    enabled: true  
  #加上超时时间
  httpclient:    connection-timeout: 10000
    
logging:  level:    org.springframework: DEBUG